version: "3.5"

# Docker Volumes
volumes:
    papermc_data2:
        name: papermc_data2

# Docker services
services:
    papermc:
        build: .
        container_name: papermc2
        restart: always
        tty: true
        stdin_open: true
        ports:
            - "25575:25565"
        volumes:
            - papermc_data2:/data
        labels:
            - "traefik.enable=true"
            - "traefik.tcp.routers.minecraft.entrypoints=minecraft"
            - "traefik.tcp.routers.minecraft.rule=HostSNI(`*`)"
            - "traefik.tcp.routers.minecraft.service=minecraft"
            - "traefik.tcp.routers.minecraft.tls=true"
            - "traefik.tcp.services.minecraft.loadbalancer.server.port=25565"
