version: "3.5"

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "25565:25565"  # Puerto TCP para Minecraft
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro  # Monta tu configuración personalizada de HAProxy si es necesario
    networks:
      - backend
      
  minecraft:
    build: .
    container_name: minecraft
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "25555:25575"  # Puerto TCP para Minecraft
    networks:
      - backend

networks:
  backend:
    driver: bridge
