version: "3.5"

# Docker services
services:
  reverse-proxy:
    # Traefik v3 docker image
    image: traefik:v3.0
    # Enables the insecure API and tells Traefik to listen to docker
    command: 
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:8055  # HTTP entrypoint
      - --serversTransport.insecureSkipVerify=true  # Ignora la verificación SSL/TLS

    ports:
      - "8055:8055"   # Expose HTTP port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket


  papermc:
    build: .
    container_name: papermc
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.papermc.rule=HostSNI(`softvercraft.softver.cc`)"
      - "traefik.tcp.routers.papermc.entrypoints=minecraft"
    restart: always
    tty: true
    
    stdin_open: true
    ports:
      - "25565:25565"  # Expose Minecraft TCP port
