version: "3.5"

# Docker services
services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.0
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:8055  # Cambia el puerto HTTP a 8080
    ports:
      # Puertos expuestos
      - "8055:8055"   # Puerto HTTP
    volumes:
      # Monta el socket de Docker para escuchar eventos de Docker
      - /var/run/docker.sock:/var/run/docker.sock

  papermc:
    build: .
    container_name: papermc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.papermc.rule=Host(`softvercraft.softver.cc`)"
      - "traefik.http.routers.papermc.entrypoints=web"
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
